### ISSUE TITLE
Set up repo

### ISSUE THREAD

**Issue by guitar-etc** [guitar-etc/Demo#1]
Before enhancing the application, I need to first set up the repo.
I'll use the following tech stack just because I think I'm most familiar with it at the moment.
- Python
- FastAPI
- AWS
- pytest
- etc.

tasks
- [x] set up dependency management 
    - [x] set up poetry #2 
- [x] build the simplest logic ever
    - #3
    - [x] `health_check` return True #4
- [x] set up lint and formatter #5
- #6
- [x] set up scripts #7
    - [x] repository init script after clone
    - [x] repository format script
    - [x] repository lint script #5
    - [x] repository test script
    - [x] repository push script: format + lint + test + push
- [x] set up CI #8
    - github actions
    - used cache to speed up
    - whether lint_format raises an error if something is changed is up in the air. I'll look into it when it turns out that it doesn't error.
- [x] set up cli #13
- [ ] set up server
    - [ ] build http server
    - [ ] set up aws
    - [ ] set up CD. deploy to aws
